print("Python"[1])
print("A sztringek karaktersorozatok"[5])
print(len("csodálatos"))
print("Rejtély"[:4])
print("k" in "Körte")
print("barack" in "sárgabarack")
print("körte" not in "Ananász")
print("barack" > "sárgabarack")
print("ananász" < "Barack")